# Generated by Django 6.0 on 2025-12-19 01:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_number", models.IntegerField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("empty", "Empty"),
                            ("occupied", "Occupied"),
                            ("reserved", "Reserved"),
                        ],
                        default="empty",
                        max_length=10,
                    ),
                ),
                ("user_name", models.CharField(blank=True, max_length=100, null=True)),
                ("reserved_at", models.DateTimeField(blank=True, null=True)),
                ("last_detected_at", models.DateTimeField(blank=True, null=True)),
                ("auto_released", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["seat_number"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text", models.TextField()),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("published_date", models.DateTimeField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="blog_image/%Y/%m/%d/"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
